### ISSUE TITLE
"Undefined" property passes validation even if set to "required"

### ISSUE THREAD

**Issue by Krzychu81** [swagger-model-validator/swagger-model-validator#127]
Definition:
````
Model:
    type: "object"
    required:
      - propertyOfModel
    properties:
      propertyOfModel:
        type: "string"
````

This object will pass the the validation:
```
{
  propertyOfModel: undefined
}
```

Potential fix:
Change 'modelValidator.js' line 651 from
```
if(!object.hasOwnProperty(property) || object[property] === "" || 
(object[property] === null && !modelFields[property]['x-nullable'] === true 
&& !modelFields[property]['nullable'] === true )) {
```
to
````
if(!object.hasOwnProperty(property) || object[property] === "" || 
object[property] === undefined ||
(object[property] === null && !modelFields[property]['x-nullable'] === true 
&& !modelFields[property]['nullable'] === true )) {
````
