### ISSUE TITLE
usage of nested definitions (question)

### ISSUE THREAD

**Issue by Sadac** [swagger-model-validator/swagger-model-validator#136]
Hi, first of all, thank you for this great library!

I'm having problems with nested definitions, so any help will be really appreciated

```yaml
responses:
  "200":
    description: This is the response schema
      schema:
        $ref: '#/definitions/UserPodsCountResponseSchema'
```
Then I have inside my `definitions:`
```yaml
UserPodsCountResponseSchema:
    type: array
    items:
      $ref: '#/definitions/UserPodsCountResponseSchema_inner'
```
And finally
```yaml
UserPodsCountResponseSchema_inner:
    type: object
    required: true
      - userId
      - count
    properties:
      userId:
        type: string
        format: uuid
        description: User ID
      count:
        type: integer
        description: Total pods to which it belongs
```
I was trying  this code in my test
```javascript
const validation = validator.validate(
  res._getData(), // [ { userId: '52bb89c8-0c4b-432d-8960-30c0b1c1e158', count: 1 } ]
  spec.paths['/user/count'].get.responses[HttpStatus.OK].schema, //  '$ref': '#/definitions/UserPodsCountResponseSchema' }
  spec.definitions,
  false,
  true,
);
```
I'm getting this on a try/catch
`Error: fields must be an array of required fields`
But I can't figure out how to implement though
