### ISSUE TITLE
The Any Type is not handled properly with nullable: true

### ISSUE THREAD

**Issue by karopolopoulos** [swagger-model-validator/swagger-model-validator#141]
When there is a schema that has `nullable` set to `true` and doesn't specify a type that schema should be considered to allow type including `null` as per https://swagger.io/docs/specification/data-models/data-types/

```
components:
  schemas:
    anyValue:
      nullable: true
      description: Can be any value, including `null`.
      example: 1234
```

I found that if I use the above schema I receive an error stating `anyValue (false) is not a type of undefined` if I try to populate `anyValue` with a `boolean`
